(cl:defpackage ytu_racing_msgs-msg
  (:use )
  (:export
   "<COMMAND>"
   "COMMAND"
   "<COMMAND>"
   "COMMAND"
   "<CONE>"
   "CONE"
   "<CONE>"
   "CONE"
   "<CONEARRAY>"
   "CONEARRAY"
   "<CONEARRAY>"
   "CONEARRAY"
   "<TRACK>"
   "TRACK"
   "<TRACK>"
   "TRACK"
   "<TRACKCONE>"
   "TRACKCONE"
   "<TRACKCONE>"
   "TRACKCONE"
   "<WAYPOINT>"
   "WAYPOINT"
   "<WAYPOINT>"
   "WAYPOINT"
   "<WAYPOINTSARRAY>"
   "WAYPOINTSARRAY"
   "<WAYPOINTSARRAY>"
   "WAYPOINTSARRAY"
  ))

